[package]
name = "hestia-lang"
version = "0.1.0"
edition = "2021"

[lib]
name = "hestia"
path = "src/lib.rs"

[[bin]]
name = "repl"
path = "src/bin/repl.rs"

[dependencies]
rustyline = "12.0.0"

[dev-dependencies]
pretty_assertions = "1.3.0"
